### ISSUE TITLE
Npm and Peer dependencies

### ISSUE THREAD

**Issue by spock123** [onehungrymind/electrogram#2]
This is not really anissue report, but just wanted to note that I had some trouble running "npm install" , because I didn't have the very latest node version installed.

LTS node (4.4.4) fails on npm install with the classical:

```
npm ERR! Darwin 14.5.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.2.3
npm ERR! npm  v2.14.7
npm ERR! code EPEERINVALID

npm ERR! peerinvalid The package rxjs@5.0.0-beta.7 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer @angular/core@2.0.0-rc.1 wants rxjs@5.0.0-beta.6
```

I tried with Node 4.2.3 and 0.10.35 

Finally managed to get it to work by using absolutely latest Node version (6.1.0) and npm 3.8.6.

So: if you have an older (or just LTS ) Node installed on your system, make sure you install this project with the latest Node. This might be good to put in the README

To juggle the different versions of Node in your local system, I recommend using the excellent nvm package.

Cheers, and thanks for a great repo.

**Comment by jdgarvey** [comment]
@spock123 Good catch on this, we've updated the README. Thanks!
